# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f226deb97d97f47e8406cbe1363871b03c070531a4be417e4431ebfd1fb424d3d852ec645f39888797786be8e43e6c10e9960437d8a5d719992dc6fe4297122

test:
  secret_key_base: 9f32006ec6e44dcf9da261afb3b997f052e8c50cf25cb48a0f8c61882fb9309393e50f817baea70ffc7dbe12f4179c6ea91b01ac21f141a19ea76c88b048c054

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
